### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pwright** [sawhney17/logseq-github-plugin#1]
Using logseq 0.6.5 and don't see anything after command 'GitHub Sync'

BTW: Thanks for your plugins

**Comment by sawhney17** [comment]
It’s an issue with the marketplace, I’ve submitted a PR upstream to the marketplace repo, once that’s merged it should work, you can currently load manually.

**Comment by pwright** [comment]
Unfortunately, it still doesn't work for me.. but no problem, will come back to marketplace when updated

**Comment by sawhney17** [comment]
Fixed it now. Turns out github secrets wasn't working as well

**Comment by sawhney17** [comment]
Marketplace version should now work as well
